In [56]:
import numpy as np
import sympy

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## Exercise 1 - Create a new 3x3 matrix. Extract 2 values via indexing.

    [[1402,191],
     [1371,821],
     [949,1437]]
     

In [14]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
arr[:-1, 1]

array([1, 4])

## Exercise 2 - Add, Subtract, Multiply and Divide 2 Matrices

    [[0, 4],
     [2, 0]]

    [[-1, 2],
     [1, -2]]

In [17]:
a = np.array([[0, 4], [2, 0]])
b = np.array([[-1, 2], [1, -2]])
a
b

array([[0, 4],
       [2, 0]])

array([[-1,  2],
       [ 1, -2]])

### Element Wise Addition

In [18]:
a + b

array([[-1,  6],
       [ 3, -2]])

### Element Wise Subtraction

In [19]:
a - b

array([[1, 2],
       [1, 2]])

### Element Wise Multiplication

In [20]:
a * b

array([[0, 8],
       [2, 0]])

### Matrix Multiplication

In [73]:
np.dot(a, b)

array([[ 5,  4],
       [11, 10]])

### Element Wise Division

In [21]:
a / b

array([[-0.,  2.],
       [ 2., -0.]])

## Exercise 3 - Create a 3x3 Identity Matrix. Show that for any matrix A, AI=IA=A.

    [[4,2,1],
     [4,8,3],
     [1,1,0]]

In [23]:
eye = np.identity(3)
eye

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
arr = np.array([[4, 2, 1], [4, 8, 3], [1, 1, 0]])
arr

array([[4, 2, 1],
       [4, 8, 3],
       [1, 1, 0]])

In [40]:
a_i = np.dot(arr, eye)
a_i

array([[ 4.,  2.,  1.],
       [ 4.,  8.,  3.],
       [ 1.,  1.,  0.]])

In [41]:
i_a = np.dot(eye, arr)
i_a

array([[ 4.,  2.,  1.],
       [ 4.,  8.,  3.],
       [ 1.,  1.,  0.]])

In [42]:
np.equal(a_i, i_a)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [43]:
np.equal(i_a, arr)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

## Exercise 4 - Transpose a Matrix. What do we need to pivot a matrix?

    [[0 1]
     [2 3]
     [4 5]]

In [44]:
arr = np.array([[0, 1], [2, 3], [4, 5]])
arr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [45]:
arr.T

array([[0, 2, 4],
       [1, 3, 5]])

To pivot a matrix chose the row with the most zero elements not located in the left most column.

## Exercise 5 - Invert a Matrix. What happens when a matrix is not invertible?

    [[1, 4],
     [2, 0]]

In [74]:
np.linalg.inv(np.array([[1, 4], [2, 0]]))

array([[ 0.   ,  0.5  ],
       [ 0.25 , -0.125]])

If a matrix is not invertible it possesses a determinate equal to zero.

## Exercise 6 - Find the determinant for the following 3 matrices.

        [[1, 2], 
         [3, 4]], 
        
        [[1, 2], 
         [2, 1]],
        
        [[1, 3],
         [3, 1]]

In [52]:
a = np.arange(1, 5, 1).reshape(2, 2)
a
b = np.array([[1, 2], [2, 1]])
b
c = np.array([[1, 3], [3, 1]])
c

array([[1, 2],
       [3, 4]])

array([[1, 2],
       [2, 1]])

array([[1, 3],
       [3, 1]])

In [53]:
np.linalg.det(a)

-2.0000000000000004

In [54]:
np.linalg.det(b)

-2.9999999999999996

In [55]:
np.linalg.det(c)

-8.0000000000000018

## Exercise 6 - Solve the following linear system.

- 3x + y = 9
- x + 2y = 8

In [61]:
sympy.Matrix(np.array([[3, 1, 9], [1, 2, 8]])).rref()

(Matrix([
 [1.0,   0, 2.0],
 [  0, 1.0, 3.0]]), [0, 1])

## Exercise 7 - Compute the eigenvalues and eigenvectors for the following matrix. What do these represent?

    [[1, 2, 1],
     [6, -1, 0],
     [-1, -2, -1]]

In [72]:
matrix = sympy.Matrix(np.array([[1, 2, 1], [6, -1, 0], [-1, -2, -1]]))
eigenvalues = matrix.eigenvals()
eigenvalues
eigenvectors = matrix.eigenvects()
eigenvectors

{-4: 1, 0: 1, 3: 1}

[(-4.00000000000000, 1, [Matrix([
   [-1.0],
   [ 2.0],
   [ 1.0]])]), (0, 1, [Matrix([
   [-0.0769230769230769],
   [ -0.461538461538462],
   [                1.0]])]), (3.00000000000000, 1, [Matrix([
   [-1.0],
   [-1.5],
   [ 1.0]])])]

Eigenvectors are vectors that remain unchanged during a linear transformation.  The vector is just scaled by a value, which is the eigenvalues.